version: "3"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/get_raw_data.py

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: python /app/financial/app.py