version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: python /app/financial/app.py

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=financial_db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql